version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: star-wars-api-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: star_wars_db
      POSTGRES_USER: star_wars_user
      POSTGRES_PASSWORD: star_wars_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
